# -- Enable/disable PostGIS database
enabled: true

# -- Role of PostGIS database in this chart
component: database

# -- Override name
nameOverride: ""
# -- Override fullname
fullnameOverride: postgis

loadBalancer:
  # -- Create a LoadBalancer service for external Database access
  enabled: false

image:
  # -- [Image repository](https://kubernetes.io/docs/concepts/containers/images/)
  repository: postgis/postgis
  # -- [Image pull policy](https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy)
  pullPolicy: IfNotPresent
  # -- Overrides the image tag whose default is the chart `appVersion`.
  tag: ""

# -- [Image pull secrets](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/)
imagePullSecrets: []

# -- Additional pod annotations
podAnnotations: {}

serviceAccount:
  # -- Specifies whether a service account should be created
  create: false
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# -- [k8s: Security context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/)
podSecurityContext: {}
  # fsGroup: 2000

# -- [k8s: Security context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/)
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# -- Database port
port: 5432
# -- Database name
dbname: ckan_default

auth:
  # -- Database username of the rw user. Database RW username for CKAN and CKAN datastore DB.
  # Note: This value is overwritten by `global.db.auth.username`, if set.
  username: ckan
  # -- Database password of the rw user. Database RW username for CKAN and CKAN datastore DB.
  # Note: This value is overwritten by `global.db.auth.password`, if set.
  password: changeMe

authRO:
  # -- Database password of the ro user. Database RO username for CKAN and CKAN datastore DB.
  # Note: This value is overwritten by `global.db.authRO.username`, if set.
  username: datastore_ro
  # -- Database password of the ro user. Database RO username for CKAN and CKAN datastore DB.
  # Note: This value is overwritten by `global.db.authRO.password`, if set.
  password: changeMe

# -- Extra environment variables for PostGIS.
extraEnv: {}

persistence:
  # -- StorageClass to use, leave empty to use default StorageClass.
  storageClassName:
  # -- Mount path of the storage. Omit trailing `/` !
  mountPath: /mydata
  # -- Subpath inside `mountPath` for the postgres data folder
  pgdataSubPath: /pgdata
  # -- Storage [access modes](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes)
  accessModes:
    - ReadWriteOnce
  # -- Storage [capacity](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#capacity)
  capacity: 4Gi
  # -- Additional annotations for PVC
  # Set helm.sh/resource-policy: keep to avoid deletion of PVC on helm upgrade/uninstall
  annotations: {}
    # helm.sh/resource-policy: keep

resources:
  limits:
    # -- [k8s: Resource management](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/)
    cpu: 2000m
    # -- [k8s: Resource management](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/)
    memory: 4Gi
  requests:
    # -- [k8s: Resource management](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/)
    cpu: 1000m
    # -- [k8s: Resource management](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/)
    memory: 2Gi

# -- [k8s: Assign pods to nodes](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/)
nodeSelector: {}
# -- [k8S: Taints and tolerations](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/)
tolerations: []
# -- [k8s: Assign pods to nodes](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/)
affinity: {}
