apiVersion: v2
name: sddi-ckan
description: A Helm chart for Kubernetes
type: application
version: 0.1.2
appVersion: "1.16.0"
dependencies:
  - name: postgis
    version: "*"
    condition: postgis.enabled
  - name: solr
    version: "*"
    condition: solr.enabled
  - name: redis
    version: "*"
    condition: redis.enabled
  - name: ckan
    version: "*"
    condition: ckan.enabled
  - name: datapusher
    version: "*"
    condition: datapusher.enabled
  - name: certIssuer
    version: "*"
    condition: certIssuer.enabled
