# -- Override name
nameOverride: ""
# -- Override fullname
fullnameOverride: ""

global:
  # -- Fully qualified domain name, used for all Ingress routes.
  # Use localhost for local testing deployments.
  ingress:
    # -- Name of the [IngressClass](https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class)
    # to use in Ingress routes.
    className: nginx
    # -- List of [FQDNs](https://de.wikipedia.org/wiki/Fully-Qualified_Host_Name) for this Ingress.
    # Note: All FQDNs will be used for Ingress hosts and TLS certificate.
    # The global setting overwrites this setting in subcharts.
    domains:
      - localhost
    certManager:
      # -- eMail address for ACME registration with Let's Encrypt. Only used for issuerType = namespace.
      issuerEmail: me@example.com
      # -- Type of [cert-manager](https://cert-manager.io/docs/) Issuer: Use either "namespace" or "cluster".
      issuerType: namespace
      # -- Name of the Issuer to use. For certManager.type = namespace
      # `letsencrypt-staging`, `letsencrypt-production` and `self-signed` are available.
      issuerName: letsencrypt-staging

  db:
    port:
    auth:
      username:
      password:
    authRO:
      username:
      password:

postgis:
  enabled: true

  loadBalancer:
    enabled: false

solr:
  enabled: true

  loadBalancer:
    enabled: false

redis:
  enabled: true

  persistence:
    enabled: false

  loadBalancer:
    enabled: false

datapusher:
  enabled: true
