# -- Override name
nameOverride: ""
# -- Override fullname
fullnameOverride: ""

global:
  ingress:
    # -- Name of the [IngressClass](https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class)
    # to use in Ingress routes.
    className: nginx
    certManager:
      # -- eMail address for ACME registration with Let's Encrypt. Only used for issuerType = namespace.
      issuerEmail: me@example.com

# Nginx ingress configuration -------------------------------------------------
# This needs to be enabled, if you don't have nginx-ingress installed already
# in your cluster.
ingress-nginx:
  enabled: true

# cert-manager configuration --------------------------------------------------
# Disable cert-manager and certIssuer for local testing, they are not required.
# Nginx ingress will create a self-signed certificate for testing automatically.

# If you want to try out cert-manager, make sure install CRDs BEFORE you install the chart.
# Make sure to enable certIssuer and configure ingress settings accordingly, see above.
# For local testing issuerType = namespace and issuerName = self-signed is recommended.
# (see here: https://cert-manager.io/docs/installation/helm/#3-install-customresourcedefinitions )
cert-manager:
  enabled: false

certIssuer:
  enabled: false

# ckan configuration ----------------------------------------------------------
ckan:
  enabled: true

  persistence:
    enabled: false

  siteUrl: https://localhost

  # Readyness and liveness checks -----------------------------------------------
  startup:
    # -- Inital delay seconds for the startup probe.
    initialDelaySeconds: 60
    # -- Check interval for the startup probe
    periodSeconds: 10
    # -- Failure threshold for the startup probe
    failureThreshold: 60
    # -- Timeout interval for the startup probe
    # Note: The CKAN pod may take some time to startup on slow systems, e.g. one
    # testing clusters. Make sure to set this value high enough to avoid the pod
    # being restarted before it has fully initialized.
    timeoutSeconds: 10
