{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
metadata:
  name: {{ include "postgresql-ha-initializer.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "postgresql-ha-initializer.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: sddi-ckan
    app.kubernetes.io/component: {{ .Values.component }}
data:
  initdb.sql: |
    -- Create PostGIS extension in default (=CKAN) database
    CREATE EXTENSION IF NOT EXISTS postgis;
    ALTER VIEW geometry_columns OWNER TO {{ .Values.global.db.auth.username | default .Values.db.auth.username | quote }};
    ALTER TABLE spatial_ref_sys OWNER TO {{ .Values.global.db.auth.username | default .Values.db.auth.username | quote }};

    -- Create datastore users
    -- read-only
    CREATE ROLE {{ .Values.global.datastore.auth.ro.username | default .Values.datastore.auth.ro.username | quote }}
      NOSUPERUSER NOCREATEDB NOCREATEROLE LOGIN PASSWORD {{ .Values.global.datastore.auth.ro.password | default .Values.datastore.auth.ro.password | squote }};

    -- read-write
    CREATE ROLE {{ .Values.global.datastore.auth.rw.username | default .Values.datastore.auth.rw.username | quote }}
      SUPERUSER NOCREATEDB NOCREATEROLE LOGIN PASSWORD {{ .Values.global.datastore.auth.rw.password | default .Values.datastore.auth.rw.password | squote }};

    -- WIP: Create datastore database owned by datastore rw user
    CREATE DATABASE {{ .Values.global.datastore.dbname | default .Values.datastore.dbname | quote }} OWNER
      {{ .Values.global.datastore.auth.rw.username | default .Values.datastore.auth.rw.username | quote }} ENCODING 'utf-8';

    -- WIP: Grant ckan db user access to datastore db
    GRANT ALL PRIVILEGES ON DATABASE {{ .Values.global.datastore.dbname | default .Values.datastore.dbname | quote }}
     TO {{ .Values.global.db.auth.username | default .Values.db.auth.username | quote }};

    -- WIP: Grant datastore ro user connect on datastore db
    GRANT CONNECT ON DATABASE {{ .Values.global.datastore.dbname | default .Values.datastore.dbname | quote }}
      TO {{ .Values.global.datastore.auth.ro.username | default .Values.datastore.auth.ro.username | quote }};

{{- end -}}
