{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgis.fullname" . }}-init
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "postgis.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: sddi-ckan
    app.kubernetes.io/component: {{ .Values.component }}
data:
  initdb.sql: |-
    CREATE ROLE {{ .Values.global.db.authRO.username | default .Values.authRO.username | quote }}
      NOSUPERUSER NOCREATEDB NOCREATEROLE LOGIN PASSWORD {{ .Values.global.db.authRO.username | default .Values.authRO.password | squote }};
    CREATE DATABASE datastore OWNER {{ .Values.global.db.auth.username | default .Values.auth.username | quote }} ENCODING 'utf-8';
    GRANT ALL PRIVILEGES ON DATABASE datastore TO {{ .Values.global.db.auth.username | default .Values.auth.username | quote }};

    CREATE EXTENSION POSTGIS;
    ALTER VIEW geometry_columns OWNER TO {{ .Values.global.db.auth.username | default .Values.auth.username | quote }};
    ALTER TABLE spatial_ref_sys OWNER TO {{ .Values.global.db.auth.username | default .Values.auth.username | quote }};

{{- end -}}
