apiVersion: v2
name: sddi-ckan
description: >
  Helm Chart for a SDDI enabled CKAN catalog.
  See [CHANGELOG](https://github.com/tum-gis/sddi-ckan-k8s/blob/main/CHANGELOG.md) for changes.
type: application
home: https://github.com/tum-gis/sddi-ckan-k8s
sources:
  - https://github.com/tum-gis/sddi-ckan-k8s
  - https://www.asg.ed.tum.de/en/gis/projects/smart-district-data-infrastructure

version: 0.3.2
appVersion: "0.0.1"
kubeVersion: ">= 1.23.0"

maintainers:
  - email: b.willenborg@tum.de
    name: Bruno Willenborg
    url: https://www.asg.ed.tum.de/en/gis/our-team/staff/bruno-willenborg/

dependencies:
  - name: postgis
    version: "*"
    condition: postgis.enabled
  - name: solr
    version: "*"
    condition: solr.enabled
  - name: redis
    version: "*"
    condition: redis.enabled
  - name: ckan
    version: "*"
    condition: ckan.enabled
  - name: datapusher
    version: "*"
    condition: datapusher.enabled
  - name: certIssuer
    version: "*"
    condition: certIssuer.enabled
  - name: ingress-nginx
    alias: ingress-nginx
    condition: ingress-nginx.enabled
    version: "~4.4.0"
    repository: https://kubernetes.github.io/ingress-nginx
  - name: cert-manager
    alias: cert-manager
    condition: cert-manager.enabled
    version: "~1.11.0"
    repository: https://charts.jetstack.io
  - name: postgresql-ha
    alias: postgresql-ha
    condition: postgresql-ha.enabled
    version: "<=9.4.11"
    repository: https://charts.bitnami.com/bitnami
  - name: postgresql-ha-initializer
    alias: psqlinit
    version: "*"
    condition: postgresql-ha-initializer.enabled
