{{- if .Values.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgis.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "postgis.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: sddi-ckan
    app.kubernetes.io/component: {{ .Values.component }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.global.db.auth.postgresUsername | default .Values.db.auth.postgresUsername }}
  POSTGRES_PASSWORD: {{ .Values.global.db.auth.postgresPassword | default .Values.db.auth.postgresPassword }}
{{- end -}}
