{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgis.fullname" . }}-init
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "postgis.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: sddi-ckan
    app.kubernetes.io/component: {{ .Values.component }}
data:
  01_createRoles.sh: |
    #!/bin/bash
    set -e

    echo "Create roles..."

    export PGPASSWORD="$POSTGRES_PASSWORD"
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL

    -- CKAN role
    DO
    \$do\$
    BEGIN
      IF EXISTS (
          SELECT FROM pg_catalog.pg_roles
          WHERE  rolname = {{ .Values.global.db.auth.username | default .Values.db.auth.username | squote }}) THEN

          RAISE NOTICE 'Role {{ .Values.global.db.auth.username | default .Values.db.auth.username | quote }} already exists. Skipping.';
      ELSE
        CREATE ROLE {{ .Values.global.db.auth.username | default .Values.db.auth.username | quote }}
          SUPERUSER NOCREATEDB NOCREATEROLE LOGIN
          PASSWORD {{ .Values.global.db.auth.password | default .Values.db.auth.password | squote }};
      END IF;
    END
    \$do\$;

    -- Datastore RW
    DO
    \$do\$
    BEGIN
      IF EXISTS (
          SELECT FROM pg_catalog.pg_roles
          WHERE  rolname = {{ .Values.global.datastore.auth.rw.username | default .Values.datastore.auth.rw.username | squote }}) THEN

          RAISE NOTICE 'Role {{ .Values.global.datastore.auth.rw.username | default .Values.datastore.auth.rw.username | quote }} already exists. Skipping.';
      ELSE
        CREATE ROLE {{ .Values.global.datastore.auth.rw.username | default .Values.datastore.auth.rw.username | quote }}
          SUPERUSER NOCREATEDB NOCREATEROLE LOGIN
          PASSWORD {{ .Values.global.datastore.auth.rw.password | default .Values.datastore.auth.rw.password | squote }};
      END IF;
    END
    \$do\$;

    -- Datastore RO
    DO
    \$do\$
    BEGIN
      IF EXISTS (
          SELECT FROM pg_catalog.pg_roles
          WHERE  rolname = {{ .Values.global.datastore.auth.ro.username | default .Values.datastore.auth.ro.username | squote }}) THEN

          RAISE NOTICE 'Role {{ .Values.global.datastore.auth.ro.username | default .Values.datastore.auth.ro.username | quote }} already exists. Skipping.';
      ELSE
        CREATE ROLE {{ .Values.global.datastore.auth.ro.username | default .Values.datastore.auth.ro.username | quote }}
          NOSUPERUSER NOCREATEDB NOCREATEROLE LOGIN
          PASSWORD {{ .Values.global.datastore.auth.ro.password | default .Values.datastore.auth.ro.password | squote }};
      END IF;
    END
    \$do\$;

    -- Datapusher
    DO
    \$do\$
    BEGIN
      IF EXISTS (
          SELECT FROM pg_catalog.pg_roles
          WHERE  rolname = {{ .Values.global.datapusher.db.auth.username | default .Values.datapusher.auth.username | squote }}) THEN

          RAISE NOTICE 'Role {{ .Values.global.datapusher.db.auth.username | default .Values.datapusher.auth.username  | quote }} already exists. Skipping.';
      ELSE
        CREATE ROLE {{ .Values.global.datapusher.db.auth.username | default .Values.datapusher.auth.username | quote }}
          SUPERUSER NOCREATEDB NOCREATEROLE LOGIN
          PASSWORD {{ .Values.global.datapusher.db.auth.password | default .Values.datapusher.auth.password  | squote }};
      END IF;
    END
    \$do\$;

    EOSQL

    echo "Create roles...done!"

  02_createDatabases.sh: |
    #!/bin/bash
    set -e

    echo "Create databases..."

    export PGPASSWORD="$POSTGRES_PASSWORD"

    # CKAN database
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -tc \
      "SELECT 1 FROM pg_database WHERE datname = {{ .Values.global.db.dbname | default .Values.db.dbname | squote }}" | grep -q 1 || \
      psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL

      CREATE DATABASE {{ .Values.global.db.dbname | default .Values.db.dbname | quote }}
      OWNER {{ .Values.global.db.auth.username | default .Values.db.auth.username | quote }}
      ENCODING 'utf-8';

    EOSQL

    # Datastore database
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -tc \
      "SELECT 1 FROM pg_database WHERE datname = {{ .Values.global.datastore.dbname | default .Values.datastore.dbname | squote }}" | grep -q 1 || \
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL

      CREATE DATABASE {{ .Values.global.datastore.dbname | default .Values.datastore.dbname | quote }}
      OWNER {{ .Values.global.datastore.auth.rw.username | default .Values.datastore.auth.rw.username | quote }}
      ENCODING 'utf-8';

    EOSQL

    # Datapusher jobs database
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -tc \
      "SELECT 1 FROM pg_database WHERE datname = {{ .Values.global.datapusher.db.dbname | default .Values.datapusher.dbname | squote }}" | grep -q 1 || \
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL

      CREATE DATABASE {{ .Values.global.datapusher.db.dbname | default .Values.datapusher.dbname | quote }}
      OWNER {{ .Values.global.datapusher.db.auth.username | default .Values.datapusher.auth.username  | quote }}
      ENCODING 'utf-8';

    EOSQL

    echo "Create databases...done!"

  03_createPostGIS.sh: |
    #!/bin/bash
    set -e

    echo "Create PostGIS..."

    export PGPASSWORD="$POSTGRES_PASSWORD"
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" \
      --dbname {{ .Values.global.db.dbname | default .Values.db.dbname | quote }} <<-EOSQL

    CREATE EXTENSION postgis;
    ALTER VIEW geometry_columns OWNER TO {{ .Values.global.db.auth.username | default .Values.db.auth.username | quote }};
    ALTER TABLE spatial_ref_sys OWNER TO {{ .Values.global.db.auth.username | default .Values.db.auth.username | quote }};

    EOSQL

    echo "Create PostGIS...done!"

  04_setDatastorePersmissions.sh: |
    #!/bin/bash
    set -e

    echo "Set datastore permissions..."

    export PGPASSWORD="$POSTGRES_PASSWORD"
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" \
      --dbname {{ .Values.global.datastore.dbname | default .Values.datastore.dbname | quote }} <<-EOSQL

      -- Datastore ro user
      GRANT CONNECT
        ON DATABASE {{ .Values.global.datastore.dbname | default .Values.datastore.dbname | quote }}
        TO {{ .Values.global.datastore.auth.ro.username | default .Values.datastore.auth.ro.username | quote }};

      GRANT SELECT ON ALL TABLES IN SCHEMA public
        TO {{ .Values.global.datastore.auth.ro.username | default .Values.datastore.auth.ro.username | quote }};

      ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT
        SELECT ON TABLES
        TO {{ .Values.global.datastore.auth.ro.username | default .Values.datastore.auth.ro.username | quote }};

      -- Datapusher user
      GRANT ALL PRIVILEGES
      ON DATABASE {{ .Values.global.datastore.dbname | default .Values.datastore.dbname | quote }}
        TO {{ .Values.global.datapusher.db.auth.username | default .Values.datapusher.auth.username | quote }};

      GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA public
        TO {{ .Values.global.datapusher.db.auth.username | default .Values.datapusher.auth.username | quote }};

    EOSQL

    echo "Alter default permissions on datastore...done!"

{{- end -}}
