{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "datapusher.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "datapusher.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: sddi-ckan
    app.kubernetes.io/component: {{ .Values.component }}
data:
  DATAPUSHER_MAX_CONTENT_LENGTH: {{ .Values.maxContentLength | squote }}
  DATAPUSHER_CHUNK_SIZE: {{ .Values.chunkSize | squote }}
  DATAPUSHER_CHUNK_INSERT_ROWS: {{ .Values.insertRows | squote }}
  DATAPUSHER_DOWNLOAD_TIMEOUT: {{ .Values.downloadTimeout | squote }}
  DATAPUSHER_SSL_VERIFY: {{ .Values.datapusherSslVerify | squote }}
  DATAPUSHER_REWRITE_RESOURCES: {{ .Values.datapusherRewriteResources | squote }}
  DATAPUSHER_REWRITE_URL: {{ .Values.datapusherRewriteUrl | squote }}
  {{- with .Values.extraEnv }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end -}}
