{{- if .Values.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ckan.fullname" . }}-{{ .Values.component }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "ckan.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: sddi-ckan
    app.kubernetes.io/component: {{ .Values.component }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ckan.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.component }}
  template:
    metadata:
      labels:
        {{- include "ckan.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ .Values.component }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      volumes:
        - name: config-ini
          configMap:
            name: {{ include "ckan.fullname" . }}-cfg-ini

      containers:
        - name: ckan
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 6379

          envFrom:
            - configMapRef:
                name: {{ include "ckan.fullname" . }}-cfg-env
            - secretRef:
                name: {{ include "ckan.fullname" . }}-sct-db
            - secretRef:
                name: {{ include "ckan.fullname" . }}-sct-smtp
            - secretRef:
                name: {{ include "ckan.fullname" . }}-sct-solr

          volumeMounts:
            # - name: data
            #   mountPath: {{ .Values.persistence.storagePath }}
            - name: config-ini
              mountPath: /srv/app/production.ini
              subPath: production.ini
              # readOnly: true

          # command:
          #   - sh
          # args:
          #   - -c
          #   - 'ls -lah /srv/app && cat /srv/app/production.ini'

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

{{- end -}}
