{{- if .Values.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ckan.fullname" . }}-sct-db
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "ckan.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: sddi-ckan
    app.kubernetes.io/component: {{ .Values.component }}
type: Opaque
stringData:
  CKAN_SQLALCHEMY_URL: {{ include "ckan.sqlalchemy.url" . | quote }}
  CKAN_DATASTORE_WRITE_URL: {{ include "ckan.datastore.rw.url" . | quote }}
  CKAN_DATASTORE_READ_URL: {{ include "ckan.datastore.ro.url" . | quote }}
  CKAN_REDIS_URL: {{ .Values.redis.url | quote }}
  CKAN_DATAPUSHER_URL: {{ .Values.datapusher.url | quote }}
{{- end -}}
