{{- if .Values.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ckan.fullname" . }}-sct-session
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "ckan.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: sddi-ckan
    app.kubernetes.io/component: {{ .Values.component }}
type: Opaque
stringData:
  CKAN___BEAKER__SESSION_KEY: {{ .Values.session.beakerSessionKey | default "ckan" | quote }}
  CKAN___BEAKER__SESSION__SECRET: {{ .Values.session.beakerSessionSecret | default (randAlphaNum 64) | quote }}
  CKAN___BEAKER_SESSION_VALIDATE_KEY: {{ .Values.session.beakerSessionValidateKey | default (randAlphaNum 64) | quote }}
{{- end -}}
