{{- if .Values.enabled -}}
{{- $defaultAPIToken :=  printf "%s%s" "string:" (randAlphaNum 64) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ckan.fullname" . }}-sct-api-token
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "ckan.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: sddi-ckan
    app.kubernetes.io/component: {{ .Values.component }}
type: Opaque
stringData:
  CKAN___API_TOKEN__NBYTES: {{ .Values.apiToken.nBytes | quote }}
  CKAN___API_TOKEN__JWT__ALGORITHM: {{ .Values.apiToken.algorithm | quote }}
  CKAN___API_TOKEN__JWT__ENCODE__SECRET: {{ .Values.apiToken.encodeSecret | default $defaultAPIToken | quote }}
  CKAN___API_TOKEN__JWT__DECODE__SECRET: {{ .Values.apiToken.decodeSecret | default $defaultAPIToken | quote }}
  {{- if .Values.datapusher.apiToken }}
  CKAN__DATAPUSHER__API_TOKEN: {{ .Values.datapusher.apiToken | quote }}
  {{- end }}
{{- end -}}
