{{- if .Values.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgis.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "postgis.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: sddi-ckan
    app.kubernetes.io/component: {{ .Values.component }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.global.db.auth.username | default .Values.db.auth.username | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.global.db.auth.password | default .Values.db.auth.password | b64enc }}
  POSTGRES_DATABASE: {{ .Values.global.db.dbname | default .Values.db.dbname | b64enc }}
{{- end -}}
