enabled: true
component: frontend
replicaCount: 1

image:
  repository: ghcr.io/keitaroinc/ckan
  tag: 2.9.5
  pullPolicy: IfNotPresent
  credentials:
    secretName: ckan-sct-pull
    registry: quay.io
    username: someone
    password: sillyness
    email: someone@host.com

imagePullSecrets:
  - name: ckan-sct-pull

# Create a LoadBalancer service for external Database access
loadBalancer:
  enabled: false

# persistence:
#   enabled: true
#   save: "60 1"
#   accessModes:
#     - ReadWriteOnce
#   capacity: 4Gi

# General settings
siteUrl: https://my-ckan.de
siteTitle: My CKAN Instance
siteDescription: This is my CKAN instance for stuff.
siteLogo: /base/images/group_icons/work.svg
favicon: /base/images/favicon.ico
siteId: my ckan_instance
maxUploadSizeMB: 250

# plugins: envvars image_view text_view recline_view datastore datapusher
plugins: envvars image_view text_view recline_view datastore datapusher

auth:
  anon_create_dataset: false
  create_unowned_dataset: false
  create_dataset_if_not_in_organization: false
  user_create_groups: false
  user_create_organizations: false
  user_delete_groups: false
  user_delete_organizations: false
  create_user_via_api: false
  create_user_via_web: true
  roles_that_cascade_to_sub_groups:  admin editor member
  public_user_details: true
  public_activity_stream_detail: true
  allow_dataset_collaborators: false
  create_default_api_keys: false

# Create a sysadmin account
# Note: Min. password length = 8 char
sysadmin:
  enabled: true
  user: admin
  password: changeMe
  email: user@example.de

dataset:
  dataset.create_on_ui_requires_resources: false

locale:
  default: de
  order: de en pt_BR ja it cs_CZ ca es fr el sv sr sr@latin no sk fi ru de pl nl bg ko_KR hu sa sl lv
  offered: de en
  filtered_out: en_GB

# Add additional CKAN settings to production.ini
# Use |+ or |- after additionalSettings only for this to work
additionalSettings: |+
  # other ckan settings
  # an even more settings

# Persistence -----------------------------------------------------------------
persistence:
  # Caution: If persistence is disabled data is stored in an emptyDir volume
  # which is ephemeral! Only for testing!
  enabled: true
  storagePath: /var/lib/ckan
  accessModes:
    - ReadWriteOnce
  capacity: 4Gi
  # Annotations for PVCs
  annotations:
    # Set helm.sh/resource-policy: keep to avoid deletion of PVC on helm upgrade/uninstall
    # helm.sh/resource-policy: keep

# CKAN database ---------------------------------------------------------------
db:
  host: &DBHost postgis-svc-headless
  port: &DBPort 5432
  dbname: &DBName ckan_default
  auth:
    username: &DBUser ckan
    password: &DBPassword changeMe

# Datastore -------------------------------------------------------------------
datastore:
  host: *DBHost
  port: *DBPort
  dbname: &DatastoreDBName datastore
  auth:
    ro:
      username: &DatastoreROUsername datastore_ro
      password: &DatastoreROUsername changeMe
    rw:
      username: &DatastoreRWUsername ckan
      password: &DatastoreRWPassword changeMe

# Redis -----------------------------------------------------------------------
redis:
  url: redis://redis-svc-headless:6379/0

# Solr ------------------------------------------------------------------------
solr:
  url: http://solr-svc-headless:8983/solr/ckan
  user:
  password:

# DataPusher ------------------------------------------------------------------
datapusher:
  url: http://datapusher-svc:8000/
  callback_url_base: http://ckan-svc:5000/

# SMTP ------------------------------------------------------------------------
smtp:
  server: "smtpServerURLorIP:port"
  user: "smtpUser"
  password: "smtpPassword"
  mailFrom: "postmaster@domain.com"
  tls: "enabled"
  startTls: "true"

# Resources -------------------------------------------------------------------
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 256Mi

# Ingress ---------------------------------------------------------------------
ingress:
  certManager:
    issuer: letsencrypt-staging

http:
  domain:
  subpath:

nodeSelector: {}
tolerations: []
affinity: {}

# Readyness and liveness checks -----------------------------------------------

readiness:
  # Inital delay seconds for the readiness probe
  initialDelaySeconds: 30
  #  Check interval for the readiness probe
  periodSeconds: 10
  # Failure threshold for the readiness probe
  failureThreshold: 6
  # Timeout interval for the readiness probe
  timeoutSeconds: 10
liveness:
  # Initial delay for the liveness probe
  initialDelaySeconds: 30
  # Check interval for the liveness probe
  periodSeconds: 10
  # Failure threshold for the liveness probe
  failureThreshold: 6
  # Timeout interval for the liveness probe
  timeoutSeconds: 10


# # Default values for ckan.
# # This is a YAML-formatted file.
# # Declare variables to be passed into your templates.

# replicaCount: 1

# image:
#   repository: nginx
#   pullPolicy: IfNotPresent
#   # Overrides the image tag whose default is the chart appVersion.
#   tag: ""

# imagePullSecrets: []
# nameOverride: ""
# fullnameOverride: ""

# serviceAccount:
#   # Specifies whether a service account should be created
#   create: true
#   # Annotations to add to the service account
#   annotations: {}
#   # The name of the service account to use.
#   # If not set and create is true, a name is generated using the fullname template
#   name: ""

# podAnnotations: {}

# podSecurityContext: {}
#   # fsGroup: 2000

# securityContext: {}
#   # capabilities:
#   #   drop:
#   #   - ALL
#   # readOnlyRootFilesystem: true
#   # runAsNonRoot: true
#   # runAsUser: 1000

# service:
#   type: ClusterIP
#   port: 80

# ingress:
#   enabled: false
#   className: ""
#   annotations: {}
#     # kubernetes.io/ingress.class: nginx
#     # kubernetes.io/tls-acme: "true"
#   hosts:
#     - host: chart-example.local
#       paths:
#         - path: /
#           pathType: ImplementationSpecific
#   tls: []
#   #  - secretName: chart-example-tls
#   #    hosts:
#   #      - chart-example.local

# resources: {}
#   # We usually recommend not to specify default resources and to leave this as a conscious
#   # choice for the user. This also increases chances charts run on environments with little
#   # resources, such as Minikube. If you do want to specify resources, uncomment the following
#   # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
#   # limits:
#   #   cpu: 100m
#   #   memory: 128Mi
#   # requests:
#   #   cpu: 100m
#   #   memory: 128Mi

# autoscaling:
#   enabled: false
#   minReplicas: 1
#   maxReplicas: 100
#   targetCPUUtilizationPercentage: 80
#   # targetMemoryUtilizationPercentage: 80

# nodeSelector: {}

# tolerations: []

# affinity: {}
