{{- if .Values.enabled -}}
{{- if not .Values.persistence.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ckan.fullname" . }}-{{ .Values.component }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "ckan.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: sddi-ckan
    app.kubernetes.io/component: {{ .Values.component }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ckan.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.component }}
  template:
    metadata:
      labels:
        {{- include "ckan.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ .Values.component }}
      annotations:
        checksum/configmap-env: {{ include (print $.Template.BasePath "/ckan-configMap-env.yml") . | sha256sum }}
        checksum/configmap-ini: {{ include (print $.Template.BasePath "/ckan-configMap-ini.yml") . | sha256sum }}
        checksum/secret-db: {{ include (print $.Template.BasePath "/ckan-sct-db.yml") . | sha256sum }}
        checksum/secret-smtp: {{ include (print $.Template.BasePath "/ckan-sct-smtp.yml") . | sha256sum }}
        checksum/secret-solr: {{ include (print $.Template.BasePath "/ckan-sct-solr.yml") . | sha256sum }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      volumes:
        - name: config-ini
          configMap:
            name: {{ include "ckan.fullname" . }}-cfg-ini
        - name: data
          emptyDir: {}

      initContainers:
        - name: set-volume-ownsership
          image: busybox
          command:
            - sh
          args:
            - -c
            - |
              mkdir -vp {{ .Values.persistence.storagePath }}
              chown -R 92:92 {{ .Values.persistence.storagePath }}

          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.storagePath }}

      containers:
        - name: ckan
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000

          envFrom:
            - configMapRef:
                name: {{ include "ckan.fullname" . }}-cfg-env
            - secretRef:
                name: {{ include "ckan.fullname" . }}-sct-db
            - secretRef:
                name: {{ include "ckan.fullname" . }}-sct-smtp
            - secretRef:
                name: {{ include "ckan.fullname" . }}-sct-solr
            {{ if .Values.sysadmin.enabled }}
            - secretRef:
                name: {{ include "ckan.fullname" . }}-sct-sysadmin
            {{ end }}

          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.storagePath }}
            - name: config-ini
              mountPath: /srv/app/production.ini
              subPath: production.ini

          readinessProbe:
            httpGet:
              path: /api/3/action/status_show
              port: 5000
            initialDelaySeconds: {{ .Values.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.readiness.periodSeconds }}
            failureThreshold: {{ .Values.readiness.failureThreshold }}
            timeoutSeconds: {{ .Values.readiness.timeoutSeconds }}

          livenessProbe:
            httpGet:
              path: /api/3/action/status_show
              port: 5000
            initialDelaySeconds: {{ .Values.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.liveness.periodSeconds }}
            failureThreshold: {{ .Values.liveness.failureThreshold }}
            timeoutSeconds: {{ .Values.liveness.timeoutSeconds }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

{{- end -}}
{{- end -}}
